/******************************************************************************/
/*            Generated by IBExpert 2024.4.7.1 19/06/2024 02:47:53            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE '127.0.0.1:C:\Desen\Delphi\BANCO_TALENTOS\db\TALENTOS.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1252;

/******************************************************************************/
/*                 Generated by IBExpert 19/06/2024 23:37:31                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   CARGOS                                   */
/******************************************************************************/


CREATE GENERATOR GEN_CARGOS_ID;

CREATE TABLE CARGOS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100) NOT NULL
);

ALTER TABLE CARGOS ADD CONSTRAINT PK_CARGOS PRIMARY KEY (ID);

SET TERM ^ ;

/* Trigger: CARGOS_BI */
CREATE OR ALTER TRIGGER CARGOS_BI FOR CARGOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cargos_id,1);
end
^
SET TERM ; ^

/******************************************************************************/
/*                                   TABLES                                   */
/******************************************************************************/

/******************************************************************************/
/*                                Vículos                                     */
/******************************************************************************/
CREATE TABLE VINCULOS (
    ID_FUNCIONARIO  INTEGER,
    ID_CARGO        INTEGER,
    ID_EMPRESA      INTEGER,
    DATA_ADMISSAO   DATE
);
ALTER TABLE VINCULOS ADD CONSTRAINT FK_VINCULOS_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGOS (ID) ON UPDATE CASCADE;
ALTER TABLE VINCULOS ADD CONSTRAINT FK_VINCULOS_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID) ON UPDATE CASCADE;
ALTER TABLE VINCULOS ADD CONSTRAINT FK_VINCULOS_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID) ON UPDATE CASCADE;

-- Inserção de registros na tabela VINCULOS
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (1, 1, 1, '2022-01-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (2, 2, 1, '2022-02-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (3, 3, 2, '2022-03-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (1, 4, 2, '2022-04-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (1, 5, 3, '2022-05-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (3, 6, 3, '2022-06-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (3, 7, 4, '2022-07-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (3, 8, 4, '2022-08-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (1, 9, 5, '2022-09-01');
INSERT INTO VINCULOS (ID_FUNCIONARIO, ID_CARGO, ID_EMPRESA, DATA_ADMISSAO) VALUES (2, 10, 5, '2022-10-01');

/******************************************************************************/
/*                                Funcionários                                */
/******************************************************************************/
CREATE GENERATOR GEN_FUNCIONARIOS_ID;

CREATE TABLE FUNCIONARIOS (
    ID         INTEGER NOT NULL,
    NOME       VARCHAR(50) NOT NULL,
    SOBRENOME  VARCHAR(50),
    EMAIL      VARCHAR(50),
    CELULAR    VARCHAR(20),
    LINKEDIN   VARCHAR(100),
    GITHUB     VARCHAR(100)
);
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (ID);

SET TERM ^ ;

/* Trigger: FUNCIONARIOS_BI */
CREATE OR ALTER TRIGGER FUNCIONARIOS_BI FOR FUNCIONARIOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_funcionarios_id,1);
end
^
SET TERM ; ^

-- Inserção de registros na tabela FUNCIONARIOS sem especificar o ID
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('JOÃO', 'SILVA', 'joao.silva@example.com', '12345-6789', 'https://linkedin.com/in/joaosilva', 'https://github.com/joaosilva');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('MARIA', 'FERNANDES', 'maria.fernandes@example.com', '98765-4321', 'https://linkedin.com/in/mariafernandes', 'https://github.com/mariafernandes');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('CARLOS', 'SANTOS', 'carlos.santos@example.com', '55555-5555', 'https://linkedin.com/in/carlossantos', 'https://github.com/carlossantos');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('ANA', 'OLIVEIRA', 'ana.oliveira@example.com', '44444-4444', 'https://linkedin.com/in/anaoliveira', 'https://github.com/anaoliveira');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('PEDRO', 'COSTA', 'pedro.costa@example.com', '33333-3333', 'https://linkedin.com/in/pedrocosta', 'https://github.com/pedrocosta');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('PAULA', 'MENDES', 'paula.mendes@example.com', '22222-2222', 'https://linkedin.com/in/paulamendes', 'https://github.com/paulamendes');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('LUCAS', 'ALMEIDA', 'lucas.almeida@example.com', '11111-1111', 'https://linkedin.com/in/lucasalmeida', 'https://github.com/lucasalmeida');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('BEATRIZ', 'LIMA', 'beatriz.lima@example.com', '66666-6666', 'https://linkedin.com/in/beatrizlima', 'https://github.com/beatrizlima');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('RAFAEL', 'CARVALHO', 'rafael.carvalho@example.com', '77777-7777', 'https://linkedin.com/in/rafaelcarvalho', 'https://github.com/rafaelcarvalho');
INSERT INTO FUNCIONARIOS (NOME, SOBRENOME, EMAIL, CELULAR, LINKEDIN, GITHUB) VALUES ('FERNANDA', 'SOUZA', 'fernanda.souza@example.com', '88888-8888', 'https://linkedin.com/in/fernandasouza', 'https://github.com/fernandasouza');

/******************************************************************************/
/*                                Cargos                                      */
/******************************************************************************/
CREATE GENERATOR GEN_CARGOS_ID;

CREATE TABLE CARGOS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100) NOT NULL
);
ALTER TABLE CARGOS ADD CONSTRAINT PK_CARGOS PRIMARY KEY (ID);

SET TERM ^ ;
/* Trigger: CARGOS_BI */
CREATE OR ALTER TRIGGER CARGOS_BI FOR CARGOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cargos_id,1);
end
^
SET TERM ; ^

-- Inserção de registros na tabela CARGOS
INSERT INTO cargos (descricao) VALUES ('GERENTE DE PROJETOS');
INSERT INTO cargos (descricao) VALUES ('DESENVOLVEDOR DE SOFTWARE');
INSERT INTO cargos (descricao) VALUES ('ANALISTA DE SISTEMAS');
INSERT INTO cargos (descricao) VALUES ('ADMINISTRADOR DE BANCO DE DADOS');
INSERT INTO cargos (descricao) VALUES ('ENGENHEIRO DE SOFTWARE');

/******************************************************************************/
/*                                Empresas                                    */
/******************************************************************************/
CREATE GENERATOR GEN_EMPRESAS_ID;

CREATE TABLE EMPRESAS (
    ID            INTEGER NOT NULL,
    RAZAO_SOCIAL  VARCHAR(100) NOT NULL,
    CNPJ          VARCHAR(20) NOT NULL
);
ALTER TABLE EMPRESAS ADD CONSTRAINT PK_EMPRESAS PRIMARY KEY (ID);

SET TERM ^ ;
/* Trigger: EMPRESAS_BI */
CREATE OR ALTER TRIGGER EMPRESAS_BI FOR EMPRESAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_empresas_id,1);
end
^
SET TERM ; ^

-- Inserção de registros na tabela EMPRESAS
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa A', '48.510.588/0001-50');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa B', '97.256.696/0001-53');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa C', '39.349.782/0001-04');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa D', '45.543.671/0001-37');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa E', '70.204.682/0001-30');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa F', '33.602.955/0001-78');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa G', '53.203.322/0001-02');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa H', '96.136.132/0001-14');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa I', '32.543.289/0001-81');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa J', '94.526.520/0001-86');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa K', '45.600.917/0001-65');
INSERT INTO EMPRESAS (RAZAO_SOCIAL, CNPJ) VALUES ('Empresa L', '96.642.818/0001-87');
/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
