/******************************************************************************/
/*            Generated by IBExpert 2024.4.7.1 19/06/2024 02:47:53            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE '127.0.0.1:C:\Desen\Delphi\BANCO_TALENTOS\db\TALENTOS.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1252;


